apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: v1
kind: Secret
metadata:
  name: gitea-mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: RootPass9015480
  MYSQL_USER: gitea_user_9015480
  MYSQL_PASSWORD: GiteaPass9015480
  MYSQL_DATABASE: gitea_db_9015480

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-mysql
spec:
  selector:
    matchLabels:
      app: gitea-mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: gitea-mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitea-mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: gitea-mysql-secret
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: gitea-mysql-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitea-mysql-secret
              key: MYSQL_PASSWORD
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: gitea-mysql-pvc

---

apiVersion: v1
kind: Service
metadata:
  name: gitea-mysql
spec:
  selector:
    app: gitea-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
